INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica generale ed inorganica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Inglese', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Stechiometria e laboratorio', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Matematica I', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Matematica II', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica organica I', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Fisica I', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica fisica I', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Fisica II', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica analitica e laboratorio', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica fisica II', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica organica II e laboratorio', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica fisica III e laboratorio', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica inorganica I', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica analitica strumentale e laboratorio', 12, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica organica III e laboratorio', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Metodologie per la determinazione di strutture molecolari', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Tirocinio', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica inorganica II e laboratorio', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Laboratorio di sintesi organica', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica industriale', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Prova finale', 3, 3, false);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Chimica'), 'Scientific english', 3, NULL, true),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica e proprietà dei materiali polimerici', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica verde', 9, NULL, true),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Chimica dei polimeri', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Spettroscopia avanzata', 12, NULL, true),
((SELECT id FROM courses WHERE name = 'Chimica'), 'Catalisi', 6, NULL, true);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Informatica'), 'Inglese', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Fondamenti di informatica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Analisi matematica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Economia aziendale', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Matematica discreta', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Elementi di informatica teorica', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Fisica computazionale', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Ricerca operativa', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Basi di dati', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Programmazione e algoritmi', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Algoritmi paralleli e sistemi distribuiti', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'User interfaces design', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Sistemi operativi', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Aspetti etici e giuridici dell''informatica', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Fondamenti di reti e sicurezza informatica', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Ingegneria del software', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Web applications', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Data driven modeling', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Intelligenza artificiale', 12, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Tirocinio', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Laboratorio di programmazione avanzata', 3, 3, false),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Prova finale', 9, 3, false);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Informatica'), 'Genere e scienza', 9, NULL, true),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Machine learning', 9, NULL, true),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Blockchain e criptovalute', 3, NULL, true),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Computer graphics', 12, NULL, true),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Cloud computing', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Informatica'), 'Internet of things', 9, NULL, true);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia aziendale', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Metodi matematici per l''economia', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Lingua inglese', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Microeconomia', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Statistica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Storia economica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Ragioneria generale ed applicata', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Diritto pubblico', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Matematica finanziaria', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Statistica ed elementi di inferenza', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Informatica', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Macroeconomia', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia industriale', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Diritto privato', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Diritto commerciale', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Tecnica e gestione degli investimenti', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Diritto amministrativo', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Politica economica', 12, 3, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia e gestione delle imprese', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Economia'), 'Prova finale', 3, 3, false);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia delle risorse umane', 12, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Modelli finanziari', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia dell''ambiente e risorse agricole', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia pubblica', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Analisi dei dati temporali e spaziali', 3, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Modelli assicurativi', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Marketing digitale', 12, NULL, true),
((SELECT id FROM courses WHERE name = 'Economia'), 'Economia internazionale', 6, NULL, true);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Fisica'), 'Laboratorio di meccanica e termodinamica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Inglese', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Informatica', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Chimica generale', 6, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Analisi matematica I', 12, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Geometria per la fisica', 9, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Meccanica e termodinamica', 12, 1, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Analisi matematica II', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Elettromagnetismo', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Meccanica superiore', 12, 2, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Laboratorio di elettromagnetismo e onde', 6, 2, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Metodi matematici della fisica', 9, 2, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Meccanica quantistica I', 12, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Elettronica', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Laboratorio di fisica moderna', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Fisica quantistica dei materiali con laboratorio', 9, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Prova finale', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Tirocinio', 6, 3, false),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Struttura della materia', 12, 3, false);

INSERT INTO course_exams (course_id, name, cfu, academic_year, is_elective) VALUES
((SELECT id FROM courses WHERE name = 'Fisica'), 'Fisica dei fluidi', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Fisica computazionale', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Fenomeni ondulatori', 3, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Ottica e laboratorio', 6, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Matematica applicata', 12, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Fisica e tecnologia dei materiali', 3, NULL, true),
((SELECT id FROM courses WHERE name = 'Fisica'), 'Astrofisica', 12, NULL, true);
